### ISSUE TITLE
Don't overwrite map(f::Function) or filter(f::Function)

### ISSUE THREAD

**Issue by tkelman** [yuehhua/ReactiveExtensions.jl#1]
as mentioned https://github.com/JuliaLang/METADATA.jl/pull/8238#issuecomment-284837949 - either use a different function name, or don't extend these from Base, or constraint to at least one input type that's defined in your package as opposed to overwriting the Base method on Base types.

**Comment by yuehhua** [comment]
I have new [commit](https://github.com/yuehhua/ReactiveExtensions.jl/commit/025fcd5dba29985130ae22820c1ed9ffa9f813b9) pushed.
So, how do I have to do next?

**Comment by tkelman** [comment]
adjust the metadata pr so the tag sha matches here. I recommend using https://github.com/attobot/attobot

**Comment by yuehhua** [comment]
@tkelman Thank you very much!
