### ISSUE TITLE
Meta: Some Projects to Borrow Ideas From

### ISSUE THREAD

**Issue by sirinath** [yuehhua/ReactiveExtensions.jl#3]
- https://monix.io/
 - https://github.com/Hopac/Hopac
 - http://www.gpars.org/
 - https://github.com/lihaoyi/scala.rx

**Comment by yuehhua** [comment]
@sirinath Thank you for providing rich reference projects.
I will add them as features to [Reactive.jl](https://github.com/JuliaGizmos/Reactive.jl).

**Comment by sirinath** [comment]
Also consider:

 - http://reactors.io/
 - http://storm-enroute.com/coroutines/

**Comment by yuehhua** [comment]
Is this project got everything done?
[Lazy.jl](https://github.com/MikeInnes/Lazy.jl)
